spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: springtest
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

# MyBatis Setup
mybatis:
  type-aliases-package: io.beaniejoy.bootapiserver.mapper
  mapper-locations: classpath:/mappers/**/*.xml